language: php
services:
  - docker
before_install:
  - docker pull registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-end
  - docker run -d --name=phpfpm registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-end
install: composer install
script:
  - docker exec -it phpfpm vendor/bin/phpcs
  - docker exec -it phpfpm vendor/bin/phpcpd Application
  - docker exec -it phpfpm vendor/bin/phpunit --stop-on-failure
  - docker exec -it phpfpm vendor/bin/phpmd ./Application text ruleset.xml
