services:
  - docker
before_install:
  - docker pull chloroplast/docker-image-phpfpm-end
  - docker run -d --name=phpfpm chloroplast/docker-image-phpfpm-end
install: docker exec -it phpfpm composer install
script:
  - docker exec -it vendor/bin/phpcs
  - docker exec -it vendor/bin/phpcpd Application
  - docker exec -it vendor/bin/phpunit --stop-on-failure
  - docker exec -it vendor/bin/phpmd ./Application text ruleset.xml
