nginx:
 image: "registry.cn-hangzhou.aliyuncs.com/marmot/nginx-phpfpm-saas:1.2"
 ports:
  - "80:80"
 links:
  - "phpfpm"
 volumes:
  - ./:/var/www/html/
 container_name: marmot-nginx

phpfpm:
  image: "registry.cn-hangzhou.aliyuncs.com/marmot/phpfpm-7.0:1.0"
  volumes:
   - ./:/var/www/html/
  links:
   - "memcached-1"
   - "memcached-2"
   - "mysql-master:mysql"
  # external_links:
  #  - "mysql-master"
   # - "mongo:mongo"
  container_name: marmot-phpfpm

mysql-master:
  image: "registry.aliyuncs.com/marmot/mysql-5.6:1.0"
  volumes:
  - ~/data/mysql/:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123456
  container_name: marmot-mysql

# mongo:
#   image: "registry.cn-hangzhou.aliyuncs.com/marmot/mongo-3.2:1.0"
#   volumes:
#    - ~/data/mongo/:/data/db
#   container_name: marmot-mongo  

memcached-1:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-memcached1

memcached-2:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-memcached2

# phpmyadmin:
#   image: "registry.aliyuncs.com/marmot/phpmyadmin:1.0"
#   links:
#    - "mysql-master:mysql"
#   ports:
#    - "10081:80"
#   environment:
#    - UPLOAD_SIZE=1G
#   container_name: marmot-phpmyadmin
    
# rockmongo:
#   image: "registry.cn-hangzhou.aliyuncs.com/marmot/rockmongo"
#   links:
#    - "mongo:db"
#   ports:
#    - "10082:80"
#   container_name: marmot-rockmongo
