nginx:
 image: "registry.cn-hangzhou.aliyuncs.com/nginx-phpfpm/nginx-end"
 ports:
  - "80:80"
 links:
  - "phpfpm"
 volumes:
  - ./:/var/www/html/
 container_name: marmot-nginx

phpfpm:
  image: "registry.cn-hangzhou.aliyuncs.com/phpfpm/phpfpm-end:dev.latest"
  volumes:
   - ./:/var/www/html/
  links:
   - "memcached-1"
   - "memcached-2"
  external_links:
   - "mysql-master:mysql"
  cap_add:
   - SYS_PTRACE
  container_name: marmot-phpfpm

memcached-1:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-memcached1

memcached-2:
  image: "registry.aliyuncs.com/marmot/memcached:1.0"
  container_name: marmot-memcached2
