phpfpm:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: type=code
  tty: true
  image: registry-internal.cn-hangzhou.aliyuncs.com/marmot/phpfpm-7.0:1.0
  volumes_from:
  - datacontainer
  stdin_open: true
datacontainer:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: type=code
  tty: true
  command:
  - bash
  - sync-config.sh
  - dev
  image: registry-internal.cn-hangzhou.aliyuncs.com/marmot/marmot-data-container:0.2
  volumes:
  - /var/www/html
  stdin_open: true
service:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: phpfpm,datacontainer
    io.rancher.scheduler.affinity:host_label: type=code
  tty: true
  image: registry-internal.cn-hangzhou.aliyuncs.com/marmot/nginx-phpfpm-saas:1.0
  volumes:
  - /log/nginx/marmot:/var/log/nginx
  volumes_from:
  - datacontainer
  stdin_open: true
