phpfpm:
  external_links:
  - Mysql/mysql:dbw
  - memcached/memcached-1:memcached_1
  - memcached/memcached-2:memcached_2
  tty: true
  image: registry.cn-hangzhou.aliyuncs.com/marmot/phpfpm-7.0:1.0
  volumes_from:
  - datacontainer
  stdin_open: true
datacontainer:
  external_links:
  - Mysql/mysql:dbw
  - memcached/memcached-1:memcached_1
  - memcached/memcached-2:memcached_2
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  command:
  - bash
  - sync-config.sh
  - dev
  image: registry.cn-hangzhou.aliyuncs.com/marmot/marmot-data-container-dev:1.0.6
  volumes:
  - /var/www/html
  stdin_open: true
nginx-1:
  external_links:
  - Mysql/mysql:dbw
  - memcached/memcached-1:memcached_1
  - memcached/memcached-2:memcached_2
  labels:
    io.rancher.sidekicks: phpfpm,datacontainer
  tty: true
  image: registry.cn-hangzhou.aliyuncs.com/marmot/nginx-phpfpm-saas:1.0
  volumes:
  - /log/nginx/marmot:/var/log/nginx
  volumes_from:
  - datacontainer
  stdin_open: true
