phpfpm:
  scale: 2
  upgrade_strategy:
    start_first: true
datacontainer:
  scale: 2
  upgrade_strategy:
    start_first: true
nginx-1:
  scale: 2
  upgrade_strategy:
    start_first: true
